<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="TestPrg" Id="{180aa939-3755-4e05-bbd0-449d032be2e9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM TestPrg
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TC_EVENTS.ST_Warning.event1;
TC_EVENTS.ST_Warning.ST_WarningEvent2;
TC_EVENTS.ST_Warning.ST_WarningEvent3;
TC_EVENTS.ST_Warning.ST_WarningEvent4;
TC_EVENTS.ST_Warning.ST_WarningEvent5;
TC_EVENTS.ST_Warning.ST_WarningEvent6;

]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>